apiVersion: v1
kind: Namespace
metadata:
  name: seminar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictive-app
  namespace: seminar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictive-app
  template:
    metadata:
      labels:
        app: predictive-app
    spec:
      containers:
        - name: predictive-app
          image: predictive-app:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: LEAK_KB_PER_REQUEST
              value: "0"
            - name: CPU_WORK_MS
              value: "10"
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: predictive-app
  namespace: seminar
spec:
  selector:
    app: predictive-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080